version: '3'
services:
  sut:
    env_file:
      - .env
    build:
      context: .
      args:
        jdbc_driver_version: ${jdbc_driver_version}
    image: liquibase-sqlite:build
    command: /opt/test_liquibase_sqlite/run_test.sh
